name: CI/CD Pipeline
 
on:
  push:
    branches: [ "master" ]                

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Echo hello world
      run: echo "Hello World"